### PR TITLE
Tweak rubocop rules and fix breakages

### PR DESCRIPTION
**Pull request by mbarnett**

### CODE REVIEW

**Comment by mbarnett** [comment]
@pgwillia fixed the original issue, but this time it failed because Jenkins was trying to run `bundle exec rake rubocop`, which isn't a rake task. 

I changed the Jenkins config to run `bundle exec rubocop` instead, but when I tried to re-run the build it errored out because it didn't know how to retrieve git metadata for the build (presumably because the "Build Now" button isn't associated with a particular commit per-se?)

**Comment by pgwillia** [comment]
@ditech-jenkins  retest this please

**Comment by pgwillia** [comment]
@mbarnett the pull request builder has some interactions that allow you to resend the job: https://github.com/ualbertalib/Developer-Handbook/tree/jenkins/Jenkins#github-pull-request-builder

**Comment by pgwillia** [comment]
retest this please

**Comment by pgwillia** [comment]
test this please

**Comment by pgwillia** [comment]
hmmm...  This was working before, I swear!

**Comment by mbarnett** [comment]
The bots are rebelling

**Comment by mbarnett** [comment]
Looks like the retest instructure is working, it's just having the same issue about git metadata.

**Comment by mbarnett** [comment]
@pgwillia possibly related to this? https://github.com/janinko/ghprb/issues/347

**Comment by pgwillia** [comment]
ok to test

**Comment by pgwillia** [comment]
@mbarnett oddly your Jenkins user(s) (see also matt) don't belong to the ualbertalib group. I have permissions tied to the github org and team. Wondering if that is related?

I don't think this is related to the issue you've cited.

**Comment by mbarnett** [comment]
Weird. On Github, I show as members of these teams in the ualbertalib organization; Developers, Developers Read-Only, and ualbertalib

**Comment by pgwillia** [comment]
Might be this though https://wiki.jenkins-ci.org/display/JENKINS/Plugins+affected+by+fix+for+SECURITY-170 | https://issues.jenkins-ci.org/browse/JENKINS-34762.  Symptom starting appearing 

```
Jun 21, 2016 3:56:08 PM hudson.model.ParametersAction filter
WARNING: Skipped parameter `sha1` as it is undefined on `hydranorth2`. Set `-Dhudson.model.ParametersAction.keepUndefinedParameters`=true to allow undefined parameters to be injected as environment variables or `-Dhudson.model.ParametersAction.safeParameters=[comma-separated list]` to whitelist specific parameter names, even though it represents a security breach
```

**Comment by pgwillia** [comment]
retest this please

**Comment by pgwillia** [comment]
retest this please

**Comment by pgwillia** [comment]
We have a workaround.  Comments still don't appear to be triggering new builds, but you should be able to trigger new builds by clicking on "Build with Parameters" giving the last commit in the pull request as the sha1 value. In any case build 34 has some more feedback for you.

**Comment by pgwillia** [comment]
Nm. rubocop is happy and my pr should deal with the spec stuff.  I'll merge and pull out the rubocop stuff from my pr.

**Comment by mbarnett** [comment]
Nice!

**Pull request merged**
